version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - err113
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - err113
        path: tests/api/
        text: do not define dynamic errors, use wrapped static errors instead
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
